### ISSUE TITLE
Baseline TODO

### ISSUE THREAD

**Issue by kojq** [kojq/Get-Arch-Linux#5]
## Why is this baseline configuration ideal for ALL desktop users for long-term use?

- [x] Eliminate desktop environment bias through stability and feature criteria
- [x] Eliminate use of popular dated packages such as `sudo`, `mkinitcpio`, and `coreutils`
- [x] Evaluate and rate each package's reliability

## Does every decision have a clear intention that positively influences the end goal?

- [x] Rewrite to incorporate archinstall or its components
- [x] Detect hardware for components such as firmware and drivers
- [x] Implement automatic btrfs snapshots with advanced universal configuration

## Is it very easy to use?

- [x] Maximize elimination of race conditions
- [x] Catch and guarantee automatic fixes for internal, external, and upstream failures without user input
  - [x] Examples: hardware failure, Secure Boot (Microsoft keys desired?), package installation errors

## Do some nuanced features work as expected?

This will likely be chaotic due to too many factors. Consequently, postpone implementation unless a solution is certain to be canonical.

- [x] Ensure hotspot functions (to and from the device)
- [x] Ensure IME functions
- [x] Ensure NTFS partitions can be mounted with the ability to read and write
- [x] Ensure notification icons exist

**Comment by kojq** [comment]
## TODO continued

- [x] A complete and simplified script eliminates several issues.

- [x] Detect device model for installation of additional packages.

- [x] Easy use of NTFS is no longer being pursued.

**Comment by kojq** [comment]
1)

Notifications, hotspot, and IME are expected from upstream and need further research.

2)

A btrfs snapshot hook or timer is worth looking into.

The main challenge is having all snapshots available as options to boot into if something goes wrong.

3)

Shifting from /boot to /efi for the ESP is difficult due to upstream and needs further research.

**Comment by kojq** [comment]
1)

I have not added Chinese and Japanese as I need to figure out the ideal choice. 

2)

Hooks can be done for updates while timers can be done for personal data.

Which one is beneficial and has minimal resource usage?

3)

Does booster accept `/efi`?

**Comment by kojq** [comment]
1)

Decide among `ibus-libpinyin`, `ibus-rime`, and `ibus-table-chinese`.

2)

Updates can destroy the system. User data can be destroyed at any time by a user or software.

If updating frequently is possible, we only need a hook (worst case loss is duration since update). However, it is not viable for when updates are the cause of issues.

If updating infrequently is possible, we only need a timer (worst case loss is the time set). However, it is not viable for when we desire the latest updates.

Consider a daily `systemd timer` for `/home` and a `pacman hook` for `/root`. Reflect each change with a `new entry` on boot.

We can have more than a week of entries. Thus, `8` sounds good (as you will know your first and last snapshots are on the same day of the week).

We need to check that these work on `limited disk space`, as disk usage varies per user and using it as a cap is thereby not a good idea. We also need ensure the latest `/home` and `/root` are `combined into the only and newest daily snapshot`.

3)

We need to test `booster` with `/efi` as ESP.

First try with `mkinitcpio` on a `test` branch.

**Comment by kojq** [comment]
1)

Done.

3)

Done.

**Comment by kojq** [comment]
Since there's only one task left, it'll continue at #8.
